[project]
name = "PolyMarketCopier"
version = "0.1.0"
description = "Copier for PolyMarket"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "py-clob-client>=0.34.4",
    "requests>=2.32.5",
]
